
version: 2.1

orbs:
    codecov: 'codecov/codecov@3.0.0'

.env_common: &env_common
    SHELL: '/bin/bash'

.env_composer: &env_composer
    COMPOSER_NO_INTERACTION: '1'
    COMPOSER_MEMORY_LIMIT: '-1'
    COMPOSER_CACHE_DIR: '/home/circleci/.cache/composer'

executors:
    php_min:
        resource_class: 'small'
        environment:
            <<: *env_common
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:7.4'

    php_plus1:
        resource_class: 'small'
        environment:
            <<: *env_common
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:8.0'

    php_plus2:
        resource_class: 'small'
        environment:
            <<: *env_common
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'cimg/php:8.1'

commands:
    php_extension_install_pcov:
        description: 'Install PHP extension – pcov'
        steps:
            -
                run:
                    name: 'Install PHP extension – pcov'
                    command: |
                        if php -m | grep pcov ; then
                            exit 0
                        fi

                        sudo pecl install pcov
                        if php -m | grep pcov ; then
                            exit 0
                        fi

                        scanDir="$(php -i | grep --color=never --only-matching --perl-regexp '(?<=^Scan this dir for additional \.ini files => ).+')"
                        echo 'extension=pcov' | sudo tee "${scanDir}/pcov.ini"

    php_extension_install_bz2:
        description: 'Install PHP extension – bz2'
        steps:
            -
                run:
                    name: 'Install PHP extension – bz2'
                    command: |
                        extName='bz2'
                        if php -m | grep "${extName}" ; then
                            echo 1>&2 "PHP extension ${extName} is already installed."

                            exit 0
                        fi

                        sudo apt-get update
                        sudo apt-get install -y libbz2-dev
                        
                        
                        if command -v docker-php-ext-install ; then
                            sudo docker-php-ext-install "${extName}"

                            exit $?
                        fi

                        phpVersion="$(php -r 'echo \PHP_VERSION;')"
                        phpUrl="https://www.php.net/distributions/php-${phpVersion}.tar.gz"
                        wget "${phpUrl}"
                        # @todo Checksum validation.
                        sudo tar xvzf "php-${phpVersion}.tar.gz" -C '/usr/local/src/'
                        rm "php-${phpVersion}.tar.gz"
    
                        cd "/usr/local/src/php-${phpVersion}/ext/${extName}"
                        sudo phpize
                        sudo ./configure
                        sudo make -j
                        sudo make install
    
                        if php -m | grep "${extName}" ; then
                            exit 0
                        fi
                        scanDir="$(php -i | grep --color=never --only-matching --perl-regexp '(?<=^Scan this dir for additional \.ini files => ).+')"
                        echo "extension=${extName}" | sudo tee --append "${scanDir}/${extName}.ini"

    composer_install:
        description: 'Install Composer dependencies with cache restore and save'
        steps:
            -
                restore_cache:
                    name: 'Composer - cache restore'
                    keys:
                        - 'composer-{{ checksum "./composer.lock" }}-2'

            -
                run:
                    name: 'Composer - install'
                    command: >
                        composer install --no-progress

            -
                save_cache:
                    name: 'Composer - cache save'
                    key: 'composer-{{ checksum "./composer.lock" }}-2'
                    paths:
                        - '~/.cache/composer/'


    lint:
        description: 'Run linters'
        steps:
            -
                run:
                    name: 'Run linters'
                    command: |
                        "$(composer config bin-dir)/robo" -vv lint

    test:
        description: 'Run tests'
        steps:
            -
                run:
                    name: 'Codeception - unit'
                    command: |
                        "$(composer config bin-dir)/robo" test unit
            -
                codecov/upload:
                    flags: 'unit'
                    file: './tests/_log/machine/coverage/unit/coverage.xml'
#            -
#                run:
#                    name: 'Codeception - acceptance'
#                    command: |
#                        "$(composer config bin-dir)/robo" test acceptance
#            -
#                codecov/upload:
#                    flags: 'acceptance'
#                    file: './tests/_log/machine/coverage/acceptance/coverage.xml'
            -
                store_test_results:
                    name: 'Store test results for CircleCI UI'
                    path: './tests/_log/machine/junit'
            -
                store_artifacts:
                    name: 'Store test results as artifacts'
                    path: './tests/_log/machine/junit'

jobs:
    build:
        executor: 'php_min'
        working_directory: '~/repo'
        steps:
            - 'php_extension_install_bz2'
            - 'checkout'
            - 'composer_install'

    # @todo PHPStan gives different results based on the actual PHP version.
    lint:
        executor: 'php_min'
        working_directory: '~/repo'
        steps:
            - 'php_extension_install_bz2'
            - 'checkout'
            - 'composer_install'
            - 'lint'
    test_php_min:
        executor: 'php_min'
        working_directory: '~/repo'
        steps:
            - 'php_extension_install_bz2'
            - 'php_extension_install_pcov'
            - 'checkout'
            - 'composer_install'
            - 'test'
    test_php_plus1:
        executor: 'php_plus1'
        working_directory: '~/repo'
        steps:
            - 'php_extension_install_bz2'
            - 'php_extension_install_pcov'
            - 'checkout'
            - 'composer_install'
            - 'test'
    test_php_plus2:
        executor: 'php_plus2'
        working_directory: '~/repo'
        steps:
            - 'php_extension_install_bz2'
            - 'php_extension_install_pcov'
            - 'checkout'
            - 'composer_install'
            - 'test'

workflows:
    lint_and_test:
        jobs:
            -
                build: {}
            -
                lint:
                    requires:
                        - 'build'
            -
                test_php_min:
                    requires:
                        - 'build'
            -
                test_php_plus1:
                    requires:
                        - 'build'
            -
                test_php_plus2:
                    requires:
                        - 'build'
